#!/usr/bin/with-contenv bash
set -e
set -u
set -o pipefail

readonly NAME=${HAA_NAME}

if [ -r "/opt/${NAME}-support/lib/lib${NAME}.sh" ];then
	. "/opt/${NAME}-support/lib/lib${NAME}.sh"
fi
#warn

function stop() {
  echo Signal
  kill $PID
}

function main() {
  echo "Starting ${NAME}"
  cat /data/bliss/install/bin/bliss.sh
  ${DAEMON} ${DAEMON_OPTIONS} ${DAEMON_EXTRA_OPTIONS} &
  PID=$!
  echo -n "$PID" > /tmp/.${NAME}_ready
  trap "stop" SIGTERM SIGINT
  trap "" SIGHUP

  echo "Wait ${PID}"
  wait "$PID"
  if [ "${DEBUG:-false}" = "true" ];then
    sleep 7d
  fi
  exit $? 
}

main
# vim: ft=sh
